// Eye state interfaces

import { Container, Graphics, Sprite } from "pixi.js";

import type { LayoutShapeName, FocusEaseName } from "./eye-types";

export type EyeInstance = {
  type: "human";
  root: Container;
  dropShadow: Sprite;
  eyeFill: Sprite;
  eyeOutline: Sprite;
  eyeShadow: Sprite;
  globeHighlight: Sprite;
  irisClipMask: Graphics;
  blinkGroup: Container;
  irisGroup: Container;
  pupilGroup: Container;
  iris: Sprite;
  pupil: Sprite;
  highlight: Sprite;
  x: number;
  y: number;
  layoutStartX: number;
  layoutStartY: number;
  targetX: number;
  targetY: number;
  layoutTransitionElapsed: number;
  layoutTransitionActive: boolean;
  radius: number;
  scale: number;
  renderScale: number;
  lowDetail: boolean;
  appearanceUpdateInterval: number;
  appearanceAccumulator: number;
  needsAppearanceRefresh: boolean;
  delay: number;
  scaleInFinished: boolean;
  parallaxX: number;
  parallaxY: number;
  repelX: number;
  repelY: number;
  lookX: number;
  lookY: number;
  currentScaleX: number;
  currentScaleY: number;
  currentAngle: number;
  pupilScale: number;
  irisProximity: number; // For smooth color transition (0 = base, 1 = mouse color)
  focusDelayMix: number;
  focusCycleOffset: number;
  // Micro-saccade state for natural eye movement
  microSaccadeTimer: number;
  microSaccadePhase: number;
  microSaccadeX: number;
  microSaccadeY: number;
};

export type EyeFieldRuntime = {
  count: number;
  clusterRadius: number;
  layoutShape: LayoutShapeName;
  layoutTransitionDuration: number;
  layoutTransitionEase: FocusEaseName;
  layoutJitter: number;
  minEyeSize: number;
  maxEyeSize: number;
  packAttempts: number;
  spiralStepDegrees: number;
  radialExponent: number;
  staggerSeconds: number;
  randomizeStagger: boolean;
  parallaxStrength: number;
  repulsionRadius: number;
  repulsionStrength: number;
  repulsionPushSpeed: number;
  repulsionReturnSpeed: number;
  smallEyeLookSpeed: number;
  largeEyeLookSpeed: number;
  trackingBlendSpeed: number;
  pointerEaseSpeed: number;
  mouseX: number;
  mouseY: number;
  targetMouseX: number;
  targetMouseY: number;
  pointerActive: boolean;
  elapsed: number;
  trackingBlend: number;
  sharedAttentionDelay: number;
  sharedAttentionRetargetMinDelay: number;
  sharedAttentionRetargetMaxDelay: number;
  sharedAttentionBlend: number;
  sharedAttentionBlendSpeed: number;
  sharedAttentionX: number;
  sharedAttentionY: number;
  lastPointerMoveAt: number;
  nextSharedAttentionAt: number;
  shadowOpacity: number;
  dropShadowColor: number;
  dropShadowOpacity: number;
  dropShadowBlur: number;
  dropShadowSpread: number;
  roundInnerShadowColor: number;
  irisColor: number;
  mouseIrisColor: number;
  mouseIrisRadius: number;
  mouseIrisBlend: number;
  mouseIrisDecay: number;
  eyeShapeColor: number;
  roundTranslateStrength: number;
  roundHighlightScale: number;
  roundHighlightOffsetX: number;
  roundHighlightOffsetY: number;
  roundHighlightRotationDegrees: number;
  roundHighlightOpacity: number;
  roundHighlightColor: number;
  eyes: EyeInstance[];
};
