import type { ClickRepulseEaseName, FocusEaseName, LayoutShapeName } from "./eye/eye-types";

export type ControlDefinition = {
  id: string;
  label: string;
  type: "number" | "color" | "select";
  min?: number;
  max?: number;
  step?: number;
  fractionDigits?: number;
  default: number | string;
  options?: Array<{ label: string; value: string }>;
  section: string;
};

export const EASE_OPTIONS: Array<{ label: string; value: FocusEaseName }> = [
  { label: "Out Cubic", value: "out-cubic" },
  { label: "Out Sine", value: "out-sine" },
  { label: "In Out Sine", value: "in-out-sine" },
  { label: "Linear", value: "linear" },
];

export const CLICK_REPULSE_EASE_OPTIONS: Array<{ label: string; value: ClickRepulseEaseName }> = [
  { label: "Smoothstep", value: "smoothstep" },
  { label: "Linear", value: "linear" },
  { label: "In Sine", value: "in-sine" },
  { label: "Out Sine", value: "out-sine" },
  { label: "In Out Sine", value: "in-out-sine" },
  { label: "In Quad", value: "in-quad" },
  { label: "Out Quad", value: "out-quad" },
  { label: "In Out Quad", value: "in-out-quad" },
  { label: "In Cubic", value: "in-cubic" },
  { label: "Out Cubic", value: "out-cubic" },
  { label: "In Out Cubic", value: "in-out-cubic" },
  { label: "In Back", value: "in-back" },
  { label: "Out Back", value: "out-back" },
  { label: "In Out Back", value: "in-out-back" },
  { label: "Out Elastic", value: "out-elastic" },
];

export const LAYOUT_SHAPE_OPTIONS: Array<{ label: string; value: LayoutShapeName }> = [
  { label: "Circle", value: "circle" },
  { label: "Square", value: "square" },
  { label: "Triangle", value: "triangle" },
  { label: "Infinity ∞", value: "infinity" },
];

export const CONTROL_DEFINITIONS: ControlDefinition[] = [
  {
    id: "instance-count",
    label: "Base < 640",
    type: "number",
    min: 24,
    max: 800,
    step: 8,
    default: 400,
    section: "Field",
  },
  {
    id: "instance-count-sm",
    label: "sm >= 640",
    type: "number",
    min: 24,
    max: 800,
    step: 8,
    default: 400,
    section: "Field",
  },
  {
    id: "instance-count-md",
    label: "md >= 768",
    type: "number",
    min: 24,
    max: 800,
    step: 8,
    default: 400,
    section: "Field",
  },
  {
    id: "instance-count-lg",
    label: "lg >= 1024",
    type: "number",
    min: 24,
    max: 800,
    step: 8,
    default: 400,
    section: "Field",
  },
  {
    id: "instance-count-xl",
    label: "xl >= 1280",
    type: "number",
    min: 24,
    max: 800,
    step: 8,
    default: 400,
    section: "Field",
  },
  {
    id: "instance-count-2xl",
    label: "2xl >= 1536",
    type: "number",
    min: 24,
    max: 800,
    step: 8,
    default: 400,
    section: "Field",
  },
  {
    id: "layout-shape",
    label: "Shape",
    type: "select",
    default: "circle",
    options: LAYOUT_SHAPE_OPTIONS,
    section: "Field",
  },
  {
    id: "layout-transition-duration",
    label: "Shape Move",
    type: "number",
    min: 0,
    max: 2.5,
    step: 0.05,
    fractionDigits: 2,
    default: 0.8,
    section: "Field",
  },
  {
    id: "layout-transition-ease",
    label: "Shape Ease",
    type: "select",
    default: "out-cubic",
    options: EASE_OPTIONS,
    section: "Field",
  },
  {
    id: "layout-jitter",
    label: "Jitter",
    type: "number",
    min: 0,
    max: 1,
    step: 0.05,
    fractionDigits: 2,
    default: 0.25,
    section: "Field",
  },
  {
    id: "scroll-fall-exit-top-factor",
    label: "Fall Start",
    type: "number",
    min: 0,
    max: 0.5,
    step: 0.01,
    fractionDigits: 2,
    default: 0.18,
    section: "Field",
  },
  {
    id: "scroll-fall-enter-top-factor",
    label: "Return Start",
    type: "number",
    min: 0,
    max: 0.5,
    step: 0.01,
    fractionDigits: 2,
    default: 0.04,
    section: "Field",
  },
  {
    id: "min-eye-size",
    label: "Base Min",
    type: "number",
    min: 1,
    max: 90,
    step: 1,
    default: 10,
    section: "Field",
  },
  {
    id: "max-eye-size",
    label: "Base Max",
    type: "number",
    min: 20,
    max: 140,
    step: 1,
    default: 90,
    section: "Field",
  },
  {
    id: "min-eye-size-sm",
    label: "sm Min",
    type: "number",
    min: 1,
    max: 90,
    step: 1,
    default: 10,
    section: "Field",
  },
  {
    id: "max-eye-size-sm",
    label: "sm Max",
    type: "number",
    min: 20,
    max: 140,
    step: 1,
    default: 90,
    section: "Field",
  },
  {
    id: "min-eye-size-md",
    label: "md Min",
    type: "number",
    min: 1,
    max: 90,
    step: 1,
    default: 10,
    section: "Field",
  },
  {
    id: "max-eye-size-md",
    label: "md Max",
    type: "number",
    min: 20,
    max: 140,
    step: 1,
    default: 90,
    section: "Field",
  },
  {
    id: "min-eye-size-lg",
    label: "lg Min",
    type: "number",
    min: 1,
    max: 90,
    step: 1,
    default: 10,
    section: "Field",
  },
  {
    id: "max-eye-size-lg",
    label: "lg Max",
    type: "number",
    min: 20,
    max: 140,
    step: 1,
    default: 90,
    section: "Field",
  },
  {
    id: "min-eye-size-xl",
    label: "xl Min",
    type: "number",
    min: 1,
    max: 90,
    step: 1,
    default: 10,
    section: "Field",
  },
  {
    id: "max-eye-size-xl",
    label: "xl Max",
    type: "number",
    min: 20,
    max: 140,
    step: 1,
    default: 90,
    section: "Field",
  },
  {
    id: "min-eye-size-2xl",
    label: "2xl Min",
    type: "number",
    min: 1,
    max: 90,
    step: 1,
    default: 10,
    section: "Field",
  },
  {
    id: "max-eye-size-2xl",
    label: "2xl Max",
    type: "number",
    min: 20,
    max: 140,
    step: 1,
    default: 90,
    section: "Field",
  },
  {
    id: "repulsion-radius",
    label: "Repulsion",
    type: "number",
    min: 0,
    max: 220,
    step: 1,
    default: 90,
    section: "Field",
  },
  {
    id: "repulsion-push-speed",
    label: "Push Speed",
    type: "number",
    min: 1,
    max: 100,
    step: 1,
    fractionDigits: 0,
    default: 50,
    section: "Motion",
  },
  {
    id: "repulsion-return-speed",
    label: "Return Speed",
    type: "number",
    min: 0.5,
    max: 20,
    step: 0.5,
    fractionDigits: 1,
    default: 3,
    section: "Motion",
  },
  {
    id: "click-repulse-radius",
    label: "Click Radius",
    type: "number",
    min: 0,
    max: 420,
    step: 1,
    default: 400,
    section: "Field",
  },
  {
    id: "click-repulse-strength",
    label: "Click Strength",
    type: "number",
    min: 0,
    max: 220,
    step: 1,
    default: 40,
    section: "Field",
  },
  {
    id: "click-repulse-ease",
    label: "Click Ease",
    type: "select",
    default: "out-elastic",
    options: CLICK_REPULSE_EASE_OPTIONS,
    section: "Field",
  },
  {
    id: "stagger-seconds",
    label: "Stagger",
    type: "number",
    min: 0,
    max: 0.1,
    step: 0.001,
    fractionDigits: 3,
    default: 0,
    section: "Field",
  },
  {
    id: "shadow-opacity",
    label: "Inner Shadow",
    type: "number",
    min: 0,
    max: 1,
    step: 0.01,
    fractionDigits: 2,
    default: 0.4,
    section: "Appearance",
  },
  {
    id: "round-inner-shadow-color",
    label: "Shadow",
    type: "color",
    default: "#a8abad",
    section: "Appearance",
  },
  {
    id: "drop-shadow-color",
    label: "Drop Color",
    type: "color",
    default: "#4a4545",
    section: "Appearance",
  },
  {
    id: "drop-shadow-opacity",
    label: "Drop Opacity",
    type: "number",
    min: 0,
    max: 1,
    step: 0.01,
    fractionDigits: 2,
    default: 0.4,
    section: "Appearance",
  },
  {
    id: "drop-shadow-blur",
    label: "Drop Blur",
    type: "number",
    min: 0,
    max: 20,
    step: 0.1,
    fractionDigits: 1,
    default: 1.2,
    section: "Appearance",
  },
  {
    id: "drop-shadow-spread",
    label: "Drop Spread",
    type: "number",
    min: 0,
    max: 10,
    step: 0.1,
    fractionDigits: 1,
    default: 0.7,
    section: "Appearance",
  },
  {
    id: "iris-color",
    label: "Iris",
    type: "color",
    default: "#ab53ee",
    section: "Appearance",
  },
  {
    id: "eye-shape-color",
    label: "Shape",
    type: "color",
    default: "#ffffff",
    section: "Appearance",
  },
  {
    id: "background-color",
    label: "Canvas BG",
    type: "color",
    default: "#ffffff",
    section: "Appearance",
  },
  {
    id: "round-translate-strength",
    label: "Move",
    type: "number",
    min: 0,
    max: 1,
    step: 0.01,
    fractionDigits: 2,
    default: 0.9,
    section: "Motion",
  },
  {
    id: "round-highlight-scale",
    label: "Scale",
    type: "number",
    min: 0,
    max: 2,
    step: 0.01,
    fractionDigits: 2,
    default: 0.45,
    section: "Round Light",
  },
  {
    id: "round-highlight-offset-x",
    label: "Offset X",
    type: "number",
    min: -100,
    max: 100,
    step: 0.5,
    fractionDigits: 1,
    default: 10,
    section: "Round Light",
  },
  {
    id: "round-highlight-offset-y",
    label: "Offset Y",
    type: "number",
    min: -100,
    max: 100,
    step: 0.5,
    fractionDigits: 1,
    default: -12.5,
    section: "Round Light",
  },
  {
    id: "round-highlight-rotation",
    label: "Rotation",
    type: "number",
    min: -180,
    max: 180,
    step: 1,
    fractionDigits: 2,
    default: 41.25,
    section: "Round Light",
  },
  {
    id: "round-highlight-opacity",
    label: "Opacity",
    type: "number",
    min: 0,
    max: 1,
    step: 0.01,
    fractionDigits: 2,
    default: 0.7,
    section: "Round Light",
  },
  {
    id: "round-highlight-color",
    label: "Color",
    type: "color",
    default: "#fffbf2",
    section: "Round Light",
  },
];

export const SECTIONS = [
  "Field",
  "Appearance",
  "Motion",
  "Round Light",
] as const;
export type SectionName = (typeof SECTIONS)[number];

export function sanitizeHexColor(value: string | undefined, fallback: string): string {
  return typeof value === "string" && /^#[0-9a-f]{6}$/iu.test(value) ? value : fallback;
}

export function sanitizeFocusEase(
  value: string | undefined,
  fallback: FocusEaseName,
): FocusEaseName {
  return EASE_OPTIONS.some((option) => option.value === value)
    ? (value as FocusEaseName)
    : fallback;
}

export function sanitizeLayoutShape(
  value: string | undefined,
  fallback: LayoutShapeName,
): LayoutShapeName {
  return LAYOUT_SHAPE_OPTIONS.some((option) => option.value === value)
    ? (value as LayoutShapeName)
    : fallback;
}

export function sanitizeClickRepulseEase(
  value: string | undefined,
  fallback: ClickRepulseEaseName,
): ClickRepulseEaseName {
  return CLICK_REPULSE_EASE_OPTIONS.some((option) => option.value === value)
    ? (value as ClickRepulseEaseName)
    : fallback;
}
